name: Convert Notebooks to HTML

on:
  push:
    branches:
      - main  # Replace with the name of your branch
    paths:
      - '**/*.ipynb'  # Only trigger if .ipynb files are changed

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Jupyter and nbconvert
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook

      # Step 4: Convert notebooks to HTML
      - name: Convert .ipynb to HTML
        run: |
          for file in $(find . -name "*.ipynb"); do
            jupyter nbconvert --to html "$file"
          done

      # Step 5: Commit and push the generated HTML files
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add **/*.html
          git commit -m "Auto-generated HTML from notebooks"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
